"""
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

fibnum1 = 1
fibnum2 = 2
final_sum = 0

while fibnum2 <= 4000000:
    if fibnum2 % 2 == 0:
        final_sum += fibnum2
    temp_fibnum1 = fibnum1
    fibnum1 = fibnum2
    fibnum2 += temp_fibnum1

print(fibnum1)
print(fibnum2)

print(final_sum)
