"""
Solution to Problem 45 of Project Euler.

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n-1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n-1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""


def tri_n(n):
    """Return the nth triangle number."""
    return n * (n + 1) / 2


def pent_n(n):
    """Return the nth pentagonal number."""
    return n * (3 * n - 1) / 2


def hex_n(n):
    """Return the nth hexagonal number."""
    return n * (2 * n - 1)


def solve():
    """Return the next triangle/pentagonal/hexagonal number after 40775."""
    h = 143
    p = 165
    t = 285
    while True:
        while hex_n(h) <= pent_n(p):
            h += 1
        while hex_n(h) <= tri_n(t):
            h += 1
        print(h)
        hex_h = hex_n(h)
        while tri_n(t) < hex_h:
            t += 1
        while pent_n(p) < hex_h:
            p += 1
        if tri_n(t) == pent_n(p) == hex_h:
            return hex_h
        else:
            h += 1


print('Next triangle number: %d' % solve())
